Add new schema for heart rate time series and new field sleep efficiency
RADAR-base/RADAR-Schemas pull request #303
Opened 2022-03-30 01:25 UTC by lalitagarwal

This PR is related to the issue [#89](https://github.com/RADAR-base/RADAR-REST-Connector/issues/89)

Changes made in the PR:

- Add field sleep efficiency to sleep classic and stage schemas
- Add new schema for heart rate time series

2022-03-30 12:56 UTC, blootsvoets requested changes

2022-03-30 12:56 UTC, blootsvoets commented on commons/connector/fitbit/fitbit_heart_rate_timeseries.avsc
> +    { "name": "datetime", "type": "string", "doc": "Local date of device (yyyy-MM-dd)." },
please rename to `date`, and mention that this is a `ISO 8601 formatted local date (yyyy-MM-dd)`. And please add a `timeReceived` field as in other records.

2022-03-30 12:56 UTC, blootsvoets commented on commons/connector/fitbit/fitbit_heart_rate_timeseries.avsc
> +  "name": "FitbitHeartRateTimeSeries",
Just `FitbitRestingHeartRate` will do.

2022-03-30 12:56 UTC, blootsvoets commented on commons/connector/fitbit/fitbit_heart_rate_timeseries.avsc
> +    { "name": "restingHeartRate", "type": ["null", "int"], "doc": "Resting heart rate value (bpm) for the day. A sleep stage log is required to generate this value. When a classic sleep log is record
Since there are no other measurements in this record, this does not need to be nullable. If there is no value, just no record needs to be sent.

2022-04-05 10:37 UTC, yatharthranjan approved these changes
Thanks for the changes. LGTM.

@blootsvoets there is some issue with docker login, did you configure the docker secrets?

2022-04-05 10:48 UTC, blootsvoets approved these changes

2022-04-05 11:14 UTC, blootsvoets commented
The docker login does not work for external contributors (to avoid credential stealing). I could change the workflow to make it optional.

2022-04-05 11:24 UTC, yatharthranjan commented
Ok thanks, will merge this now.

2022-04-05 11:24 UTC, merged